# Extract text from each .docx in docs/ and build master_context.md with labeled summaries.
$ErrorActionPreference = "Stop"
$docsRoot = "c:\Users\samal\OneDrive\Documents\FIELDPORTER\Cursor Week 2\docs"
$projectRoot = "c:\Users\samal\OneDrive\Documents\FIELDPORTER\Cursor Week 2"
$outPath = Join-Path $projectRoot "master_context.md"
$tempBase = Join-Path $projectRoot "docx-extract-temp"
$maxChars = 1400  # Concise key points only

$ns = @{ w = "http://schemas.openxmlformats.org/wordprocessingml/2006/main" }

function Get-TextFromDocx($docxPath) {
    $zipPath = Join-Path $tempBase ([System.IO.Path]::GetFileName($docxPath) + ".zip")
    $extractDir = Join-Path $tempBase ([System.IO.Path]::GetFileNameWithoutExtension($docxPath))
    try {
        if (Test-Path $extractDir) { Remove-Item $extractDir -Recurse -Force }
        if (Test-Path $zipPath) { Remove-Item $zipPath -Force }
        Copy-Item $docxPath $zipPath -Force
        Expand-Archive -Path $zipPath -DestinationPath $extractDir -Force
        $xmlPath = Join-Path $extractDir "word\document.xml"
        if (-not (Test-Path $xmlPath)) { return $null }
        [xml]$xml = Get-Content $xmlPath -Encoding UTF8
        $texts = Select-Xml -Xml $xml -XPath "//w:t" -Namespace $ns | ForEach-Object { $_.Node.InnerText }
        $raw = ($texts -join " ").Trim()
        return $raw
    } finally {
        if (Test-Path $extractDir) { Remove-Item $extractDir -Recurse -Force -ErrorAction SilentlyContinue }
        if (Test-Path $zipPath) { Remove-Item $zipPath -Force -ErrorAction SilentlyContinue }
    }
}

function Strip-Filler($text) {
    if (-not $text) { return "" }
    # Collapse multiple spaces/newlines
    $text = [regex]::Replace($text, "\s+", " ")
    # Remove common filler lines (exact or startswith)
    $filler = @(
        "Table of Contents", "Page \d+", "^\d+\s*$",
        "Document generated", "Generated by", "Confidential",
        "All rights reserved", "Copyright \d", "\.\.\.\s*$"
    )
    foreach ($p in $filler) {
        $text = [regex]::Replace($text, "(?m)^\s*" + $p + ".*$", " ", "IgnoreCase")
    }
    $text = [regex]::Replace($text, "\s+", " ").Trim()
    return $text
}

if (Test-Path $tempBase) { Remove-Item $tempBase -Recurse -Force }
New-Item -ItemType Directory -Path $tempBase -Force | Out-Null

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine("# Master Context - Document Summaries")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("Concise key points extracted from each document in docs/. Filler removed.")
[void]$sb.AppendLine("")

$docxFiles = Get-ChildItem -Path $docsRoot -Recurse -Filter "*.docx" | Sort-Object FullName
$total = $docxFiles.Count
$n = 0

foreach ($f in $docxFiles) {
    $n++
    $relPath = $f.FullName.Substring($docsRoot.Length).TrimStart("\")
    Write-Host "[$n/$total] $relPath"
    $fullText = Get-TextFromDocx $f.FullName
    if (-not $fullText) {
        [void]$sb.AppendLine("## " + $relPath)
        [void]$sb.AppendLine("")
        [void]$sb.AppendLine("*No text extracted.*")
        [void]$sb.AppendLine("")
        continue
    }
    $cleaned = Strip-Filler $fullText
    $summary = if ($cleaned.Length -le $maxChars) { $cleaned } else { $cleaned.Substring(0, $maxChars) + "..." }
    [void]$sb.AppendLine("## " + $relPath)
    [void]$sb.AppendLine("")
    [void]$sb.AppendLine($summary)
    [void]$sb.AppendLine("")
}

[System.IO.File]::WriteAllText($outPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $outPath"
if (Test-Path $tempBase) { Remove-Item $tempBase -Recurse -Force }
